apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: gitlab-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
        team: cloud
    spec:
      containers:
      - name: webhook-container
        image: imagepath.domain.doc/registry:tagv.0.0.1
        env:
        - name: JIRA_SERVER
          valueFrom:
            secretKeyRef:
              name: webhook-secret
              key: JIRA_SERVER
        - name: JIRA_USERNAME
          valueFrom:
            secretKeyRef:
              name: webhook-secret
              key: JIRA_USERNAME
        - name: JIRA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: webhook-secret
              key: JIRA_API_TOKEN
        - name: SECRET_TOKEN  
          valueFrom:
            secretKeyRef:
              name: webhook-secret  
              key: SECRET_TOKEN
        - name: SLACK_API_TOKEN  
          valueFrom:
            secretKeyRef:
              name: webhook-secret  
              key: SLACK_API_TOKEN
        - name: GITLAB_TOKEN  
          valueFrom:
            secretKeyRef:
              name: webhook-secret  
              key: GITLAB_TOKEN
        - name: GITLAB_URL
          valueFrom:
            secretKeyRef:
              name: webhook-secret  
              key: GITLAB_URL