apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    external-dns.domain.com/private: "true"
  labels:
    app: gitlab-mr-hook-listener
    env: dev
    release: gitlab-hook-listener
    team: cloud
  name: gitlab-mr-hook-listener-private
  namespace: gitlab-webhook
spec:
  gateways:
  - istio-system/istio-ingressgateway-private
  hosts:
  - gitlab-mr-hook-listener-dev.domain.com
  http:
  - route:
    - destination:
        host: mr-webhook-service
        port:
          number: 13100
